[project]
name = "FontsCompress"
version = "0.1.0"
description = "A tool to compress font files for static websites."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fonttools>=4.59.2",
]
